primerEjemplo/Controllers/FormularioController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using primerEjemplo.Models;

namespace primerEjemplo.Controllers
{
    public class FormularioController : Controller
    {
        public IActionResult Index()
        {
            CuentaParaView cuentaParaView = new CuentaParaView();
            cuentaParaView.Cuenta = new Cuenta() {
                Id = 123,
                Disponible = true,
                Genero = "M"
            };

            cuentaParaView.Lenguajes = new List<Lenguaje>()
            {
                new Lenguaje() { Id = "len01", Nombre = "C#", Tickedo=false },
                new Lenguaje() { Id = "len02", Nombre = "Java", Tickedo=false },
                new Lenguaje() { Id = "len03", Nombre = "Python", Tickedo=false },
                new Lenguaje() { Id = "len04", Nombre = "PHP", Tickedo=false },
                new Lenguaje() { Id = "len05", Nombre = "JavaScript", Tickedo=false },
                new Lenguaje() { Id = "len06", Nombre = "Ruby", Tickedo=false },
                new Lenguaje() { Id = "len07", Nombre = "Typescript", Tickedo=false },
                new Lenguaje() { Id = "len08", Nombre = "Swift", Tickedo=false },
            };

            var cargos = new List<Cargo>()
            {
                new Cargo() { Id = "c01", Nombre = "Desarrollador" },
                new Cargo() { Id = "c02", Nombre = "Tester" },
                new Cargo() { Id = "c03", Nombre = "Administrador" },
                new Cargo() { Id = "c04", Nombre = "Gerente" }
            };

            cuentaParaView.Cargos = new SelectList(cargos, "Id", "Nombre", "c03");

            return View("Index", cuentaParaView);
        }
        [HttpPost] //action verbs (solo es alcanzable desde la peticion post)
        public IActionResult Registrar(CuentaParaView cuentaParaView, List<Lenguaje> lenguajes) {
            cuentaParaView.Cuenta.Lenguajes = new List<string>();
            foreach (var lenguaje in lenguajes)
                if (lenguaje.Tickedo)
                    cuentaParaView.Cuenta.Lenguajes.Add(lenguaje.Id);
            ViewBag.Cuenta = cuentaParaView.Cuenta;
            return View("Registrado");
        }
    }
}

primerEjemplo/Views/Formulario/Index.cshtml
@model primerEjemplo.Models.CuentaParaView;

<div class="container">
    <div class="row">
        <div class="col-sm-4"></div>
        <div class="col-sm-5">
            <form method="post" asp-controller="Formulario" asp-action="Registrar">
                <div class="col-md-12 row">
                    <label class="col-md-3"> Usuarios: </label>
                    <div class="col-md-8"><input type="text" asp-for="Cuenta.Usuario" class="form-control form-control-sm col-md-12" /></div>
                </div>
                <div class="col-md-12 row">
                    <label class="col-md-3"> Password: </label>
                    <div class="col-md-8"><input type="password" asp-for="Cuenta.Password" class="form-control form-control-sm col-md-12" /></div>
                </div>
                <div class="col-md-12 row">
                    <label class="col-md-3"> Usuarios: </label>
                    <div class="col-md-8"><textarea asp-for="Cuenta.Descripcion" class="form-control form-control-sm col-md-12" rows="4" cols="20"></textarea></div>
                </div>
                <div class="col-md-12 row">
                    <label class="col-md-3"> Disponible: </label>
                    <div class="col-md-8"><input type="checkbox" asp-for="Cuenta.Disponible" class="form-check-input col-md-12" /></div>
                </div>
                <div class="col-md-12 row">
                    <label class="col-md-3"> Genero: </label>
                    <div class="col-md-8">
                        <input type="radio" asp-for="Cuenta.Genero" value="M" class="form-check-input col-md-12" />Masculino <br/>
                        <input type="radio" asp-for="Cuenta.Genero" value="F" class="form-check-input col-md-12" />Feminino
                    </div>
                </div>
                <div class="col-md-12 row">
                    <label class="col-md-3"> Lenguajes de Programación: </label>
                    <div class="col-md-8">
                        @for (var i = 0; i < Model.Lenguajes.Count; i++)
                        {
                            <input type="hidden" asp-for="@Model.Lenguajes[i].Id"/>
                            <input type="hidden" asp-for="@Model.Lenguajes[i].Nombre" />
                            <input type="checkbox" class="form-check-input" asp-for="@Model.Lenguajes[i].Tickedo" />
                            @Model.Lenguajes[i].Nombre
                            <br />
                        }
                    </div>
                </div>
                <div class="col-md-12 row">
                    <label class="col-md-3"> Cargos: </label>
                    <div class="col-md-8">
                        <select asp-for="Cuenta.Cargo" asp-items="@Model.Cargos"></select>
                    </div>
                </div>
                <div>
                    <input type="hidden" asp-for="Cuenta.Id" />
                    <button type="submit" class="btn btn-success">Enviar</button>
                </div>
            </form>
        </div>
    </div>
</div>

primerEjemplo/Views/Formulario/Registrado.cshtml
<table class="table table-bordered">
    <tr>
        <td>Id: </td>
        <td>@ViewBag.Cuenta.Id</td>
    </tr>
    <tr>
        <td>Usuario: </td>
        <td>@ViewBag.Cuenta.Usuario</td>
    </tr>
    <tr>
        <td>Password: </td>
        <td>@ViewBag.Cuenta.Password</td>
    </tr>
    <tr>
        <td>Descripcion: </td>
        <td>@ViewBag.Cuenta.Descripcion</td>
    </tr>
    <tr>
        <td>Disponible: </td>
        <td>@ViewBag.Cuenta.Disponible</td>
    </tr>
    <tr>
        <td>Genero: </td>
        <td>@ViewBag.Cuenta.Genero</td>
    </tr>
    <tr>
        <td>Cargo: </td>
        <td>@ViewBag.Cuenta.Cargo</td>
    </tr>
    <tr>
        <td>Lenguajes de Programación: </td>
        <td>
            @foreach (var lenguaje in ViewBag.Cuenta.Lenguajes)
            {
                <span>@lenguaje</span> <br />
            }
        </td>
    </tr>
</table>